FROM openjdk:8-jdk-alpine 
VOLUME /tmp 
COPY target/PayDayTradeApiGatewayMicroservice-0.0.1-SNAPSHOT.jar PayDayTradeApiGatewayMicroservice.jar 
ENTRYPOINT ["java","-jar","PayDayTradeApiGatewayMicroservice.jar"]
