FROM openjdk:8-jdk-alpine 
VOLUME /tmp 
COPY target/PayDayTradeEurekaDiscoveryMicroservice-0.0.1-SNAPSHOT.jar PayDayTradeEurekaDiscoveryMicroservice.jar 
ENTRYPOINT ["java","-jar","PayDayTradeEurekaDiscoveryMicroservice.jar"]
